// Code generated by Arduino IoT Cloud, DO NOT EDIT.


#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "534ff531-8e29-4da6-b702-ac704f25a299";  //Enter THING ID
const char DEVICE_LOGIN_NAME[]  = "898995bd-4c31-4146-b79d-7b1c4a7dab62"; //Enter DEVICE ID

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onhalllight1Change();
void onroomlight2Change();
void onhallfan3Change();
void onkichen4Change();

CloudSwitch halllight1;
CloudSwitch roomlight2;
CloudSwitch hallfan3;
CloudSwitch kichen4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(halllight1, READWRITE, ON_CHANGE, onhalllight1Change);
  ArduinoCloud.addProperty(roomlight2, READWRITE, ON_CHANGE, onroomlight2Change);
  ArduinoCloud.addProperty(hallfan3, READWRITE, ON_CHANGE, onhallfan3Change);
  ArduinoCloud.addProperty(kichen4, READWRITE, ON_CHANGE, onkichen4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
